services:
  paste_service:
    build:
      context: .
      dockerfile: paste_service/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DB_HOST=db
      - DB_PORT=3306

    volumes:
      - ./paste_service/app:/app/app
      - ./shared:/app/shared
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - backend_network

  analytics_service:
    build:
      context: .
      dockerfile: analytics_service/Dockerfile
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./analytics_service/app:/app/app
      - ./shared:/app/shared
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - backend_network

  login_service:
    build:
      context: ./login_service # Thư mục chứa Dockerfile và package.json
      dockerfile: Dockerfile # Không cần ghi rõ nếu tên là Dockerfile
    # volumes:
    #   - ./login_service:/app # Khớp với WORKDIR trong Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
    networks:
      - backend_network
    ports:
      - "5001:5001"
    env_file:
      - .env

  cleanup_service:
    build:
      context: .
      dockerfile: cleanup_service/Dockerfile
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./cleanup_service/app:/app/app
      - ./shared:/app/shared
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "13306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend_network

volumes:
  db_data:

networks:
  backend_network:
