services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend_network

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "13306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - backend_network

volumes:
  db_data:

networks:
  backend_network:
