services:
  paste_service:
    build:
      context: .
      dockerfile: paste_service/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./paste_service/app:/app/app
      - ./shared:/app/shared
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - backend_network

  analytics_service:
    build:
      context: .
      dockerfile: analytics_service/Dockerfile
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./analytics_service/app:/app/app
      - ./shared:/app/shared
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - backend_network

  cleanup_service:
    build:
      context: .
      dockerfile: cleanup_service/Dockerfile
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./cleanup_service/app:/app/app
      - ./shared:/app/shareds
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "13306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend_network

volumes:
  db_data:

networks:
  backend_network:
